version: 0.2
env:
  shell: /bin/sh
phases:
  install:
    commands:
      - echo 'Install phase starting'
    finally:
      - echo 'Install phase completed.'
  pre_build:
    commands:
      - echo 'Pre-build phase starting'
    finally:
      - echo 'Pre-build phase completed.'
  build:
    commands:
      - echo 'Build phase starting'
      - JAVA_HOME=$JDK_8_HOME ./gradlew build
    finally:
      - echo 'Build phase completed.'
  post_build:
    commands:
      - echo 'Post-build phase starting'
      - echo $CODEBUILD_SRC_DIR
      - cp ./*/build/test-results/testReleaseUnitTest/*.xml ./allTests
      - find ./*/build/test-results -name "*.xml"
    finally:
      - echo 'Post-build phase completed.'
reports:
  amplify-android-unit-tests:
    files:
      - allTests/*
    discard-paths: yes
    file-format: JUNITXML
artifacts:
  files:
    - '**/*.apk'
  name: amplify-android-cat-apks
  discard-paths: yes
#  base-directory: location
#  secondary-artifacts:
#    artifactIdentifier:
#      files:
#        - location
#        - location
#      name: secondary-artifact-name
#      discard-paths: no | yes
#      base-directory: location
#    artifactIdentifier:
#      files:
#        - location
#        - location
#      discard-paths: no | yes
#      base-directory: location
